apiVersion: v1
kind: Service
metadata:
  name: fio-fake
  namespace: qa-space
  labels:
    app: fio
spec:
  ports:
  - port: 80
    name: fio-fake
  clusterIP: None
  selector:
    app: fio
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-task-set
  namespace: qa-space
data:
  fio-task-set.conf: |
    randrw,10,4k,16,5G
    randrw,50,4k,16,5G
    randrw,70,4k,16,5G
    randrw,10,8k,16,5G
    randrw,50,8k,16,5G
    randrw,70,8k,16,5G
    randrw,10,16k,16,5G
    randrw,50,16k,16,5G
    randrw,70,16k,16,5G
    randrw,10,32k,16,5G
    randrw,50,32k,16,5G
    randrw,70,32k,16,5G
    randrw,10,64k,16,5G
    randrw,50,64k,16,5G
    randrw,70,64k,16,5G
    randrw,10,128k,16,5G
    randrw,50,128k,16,5G
    randrw,70,128k,16,5G
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio
  namespace: qa-space
spec:
  selector:
    matchLabels:
      app: fio # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "fio-fake"
  replicas: 4
  template:
    metadata:
      labels:
        app: fio # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: fio
        image: savex13/benchmarks:fio-3-26
        imagePullPolicy: IfNotPresent
        env:
          - name: FIO_MOUNTPOINT
            value: "/data"
         # Run single fio test
          - name: FIO_TEST_SET
          #  value: "single"
            value: /tmp/fio-task-set.conf

          # Run modes: 'synced' or 'normal'
          # 'synced' rounds time down to 5min, adds 7 min
          # and waits for that time to start
          # 'normal' starts tests right away
          # - name: RUN_MODE
          #   value: "synced"

          # Test specific
          - name: FIO_NAME
            value: "single_run"

          # Test modes (default: randrw)
          # - name: FIO_READWRITE
          # Random read
          #  value: "randread"
          # Random write
          #  value: "randwrite"
          # Sequential read
          #  value: "read"
          # Sequential write
          #  value: "write"
          # Mixed random read/write
          #  value: "randrw"


          - name: FIO_BS
            value: "4k"
          - name: FIO_IODEPTH
            value: "16"
          - name: FIO_SIZE
            value: "5G"
        
          - name: FIO_RAMP_TIME
            value: "5s"
          - name: FIO_RUNTIME
            value: "90s"

          # Sequential specific
          # - name: FIO_OFFSET_INCREMENT
          #   value: "500M"
          # - name: FIO_JOBS
          #   value: "4"

          # Mixed specific
          # - name: FIO_RWMIXREAD
          #   value: "50"


          # Other options
          # - name: FIO_RANDREPEAT
          #   value: 0
          # - name: FIO_VERIFY
          #   value: 0
          # - name: FIO_IOENGINE
          #   value: libaio
          # - name: FIO_DIRECT
          #   value: 1
          # - name: FIO_GTOD_REDUCE
          #   value: 0

        volumeMounts:
        - name: fio-vol
          mountPath: /data
        - name: fio-task-set-vol
          mountPath: /tmp  
      volumes:
      - name: fio-task-set-vol
        configMap:
          name: fio-task-set
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: fio-vol
    spec:
      storageClassName: kubernetes-hdd
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
