apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio
  namespace: qa-space
spec:
  selector:
    matchLabels:
      app: pod # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  #serviceName: "nginx"
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: fio
        image: savex13/benchmarks:fio-3-26
        imagePullPolicy: IfNotPresent
        env:
          - name: FIO_MOUNTPOINT
            value: /data
         # Run single fio test
          - name: FIO_TEST_SET
            value: "single"

          # Run modes: 'synced' or 'normal'
          # 'synced' rounds time down to 5min, adds 7 min
          # and waits for that time to start
          # 'normal' starts tests right away
          # - name: RUN_MODE
          #   value: "synced"

          # Test specific
          - name: FIO_NAME
            value: single_run

          # Test modes (default: randrw)
          # - name: FIO_READWRITE
          # Random read
          #  value: randread        
          # Random write
          #  value: randwrite
          # Sequential read
          #  value: read
          # Sequential write
          #  value: write
          # Mixed random read/write
          #  value: randrw


          - name: FIO_BS
            value: 4k
          - name: FIO_IODEPTH
            value: 64
          - name: FIO_SIZE
            value: 2G
        
          - name: FIO_RAMP_TIME
            value: 5s
          - name: FIO_RUNTIME
            value: 30s

          # Sequential specific
          # - name: FIO_OFFSET_INCREMENT
          #   value: 500M
          # - name: FIO_JOBS
          #   value: 4

          # Mixed specific
          # - name: FIO_RWMIXREAD
          #   value: 50


          # Other options
          # - name: FIO_RANDREPEAT
          #   value: 0
          # - name: FIO_VERIFY
          #   value: 0
          # - name: FIO_IOENGINE
          #   value: libaio
          # - name: FIO_DIRECT
          #   value: 1
          # - name: FIO_GTOD_REDUCE
          #   value: 1

        volumeMounts:
        - name: fio-vol
          mountPath: /data
      restartPolicy: Never
  volumeClaimTemplates:
  - metadata:
      name: fio-vol
    spec:
      storageClassName: volumes-nvme
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi