kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-pvc
  #namespace: <your_namespace>
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio
  #namespace: <your_namespace>
spec:
  template:
    spec:
      containers:
      - name: fio
        image: savex13/benchmarks:fio-3-26
        imagePullPolicy: IfNotPresent
        env:
          - name: FIO_MOUNTPOINT
            value: /data
          # Run mode: 'synced' 
          # rounds time down to 5min, adds 7 min
          # and waits for that time to start
          # Run mode: 'normal'
          # Starts tests right away
          # - name: RUN_MODE
          #   value: "synced"

          # - name: FIO_TEST_SET
          #   value: "bulk"
          # - name: FIO_QUICK
          #   value: "no"
          # - name: FIO_SIZE
          #   value: 2G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 500M
          # - name: FIO_DIRECT
          #   value: "0"
          # - name: FIO_IODEPTH
          #   value: 64

          # Defaults/overide templates

          # IOPS tests (defaults)
          # - name: IOPS_BS
          #   value: 4k
          # - name: IOPS_DP
          #   value: <same as FIO_IODEPTH>

          # Bandwidth test 
          # - name: BW_BS
          #   value: 128k
          # - name: BW_DP
          #   value: <same as FIO_IODEPTH>

          # Latency test 
          # - name: LAT_BS
          #   value: 4k
          # - name: LAT_DP
          #   value: 4

          # Sequential tests
          # - name: SEQ_BS
          #   value: 1M
          # - name: SEQ_DP
          #   value: 16
          # - name: SEQ_JOBS
          #   value: 4

          # Mixed test
          # - name: MIX_BS
          #   value: 4k
          # - name: MIX_DP
          #   value: <same as FIO_IODEPTH>
          # - name: MIX_RWMIXREAD
          #   value: 75

        volumeMounts:
        - name: fio-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: fio-pv
        persistentVolumeClaim:
          claimName: fio-pvc
  backoffLimit: 4
